console.log(2 == 2); // true
console.log(2 == '2'); // true
console.log(2 == 3); // false
console.log(2 == true); // false
console.log(2 == false); // false
console.log(2 == 3); // false
console.log(2 == '1'); // false
console.log(true == 1); // true
console.log(false == 0); // true
console.log(null == undefined); // true
console.log(null == 0); // false
console.log(undefined == 0); // false
console.log(NaN == NaN); // false